apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-wide-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/AlcarisMinecraftServer/alcaris_infra
        revision: main
        directories:
          - path: manifests/apps/cluster-wide-apps/*
  template:
    metadata:
      name: "cluster-wide-apps-{{path.basenameNormalized}}"
      namespace: argocd
    spec:
      project: cluster-wide-apps
      source:
        repoURL: https://github.com/AlcarisMinecraftServer/alcaris_infra
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'cluster-wide-apps'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-wide-app-resources
  namespace: argocd
spec:
  project: argocd-root
  source:
    repoURL: https://github.com/AlcarisMinecraftServer/alcaris_infra
    targetRevision: main
    path: manifests/apps/cluster-wide-app-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: 'cluster-wide-apps'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-cloudflared-tunnel
  namespace: argocd
spec:
  project: cloudflared-tunnel
  source:
    repoURL: https://github.com/AlcarisMinecraftServer/alcaris_infra
    targetRevision: main
    path: manifests/apps/cloudflared-tunnel
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared-tunnel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alcaris-production-gateway-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/AlcarisMinecraftServer/alcaris_infra
        revision: main
        directories:
          - path: manifests/apps/alcaris-production-gateway/*
  template:
    metadata:
      name: "alcaris-production-gateway-{{path.basenameNormalized}}"
      namespace: argocd
    spec:
      project: alcaris-production-gateway
      source:
        repoURL: https://github.com/AlcarisMinecraftServer/alcaris_infra
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: alcaris-production-gateway
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
      ignoreDifferences:
        - group: ""
          kind: Service
          jsonPointers:
            - /status
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alcaris-production-minecraft-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/AlcarisMinecraftServer/alcaris_infra
        revision: main
        directories:
          - path: manifests/apps/alcaris-production-minecraft/*
  template:
    metadata:
      name: "alcaris-production-minecraft-{{path.basenameNormalized}}"
      namespace: argocd
    spec:
      project: alcaris-production-minecraft
      source:
        repoURL: https://github.com/AlcarisMinecraftServer/alcaris_infra
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: alcaris-production-minecraft
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alcaris-service-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/AlcarisMinecraftServer/alcaris_infra
        revision: main
        directories:
          - path: manifests/apps/alcaris-service/*
  template:
    metadata:
      name: "alcaris-service-{{path.basenameNormalized}}"
      namespace: argocd
    spec:
      project: alcaris-service
      source:
        repoURL: https://github.com/AlcarisMinecraftServer/alcaris_infra
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: alcaris-service
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: database-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/AlcarisMinecraftServer/alcaris_infra
        revision: main
        directories:
          - path: manifests/apps/database/*
  template:
    metadata:
      name: "database-{{path.basenameNormalized}}"
      namespace: argocd
    spec:
      project: database
      source:
        repoURL: https://github.com/AlcarisMinecraftServer/alcaris_infra
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: database
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
