apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-wide-apps
  namespace: argocd
spec:
  description: The project of applications used by the entire cluster
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'cluster-wide-apps'
      server: https://kubernetes.default.svc
    - namespace: 'kube-system'
      server: https://kubernetes.default.svc
    - namespace: 'metallb-system'
      server: https://kubernetes.default.svc
    - namespace: "local-path-storage"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloudflared-tunnel
  namespace: argocd
spec:
  description: The project of service system for the cloudflared tunnel (prod)
  sourceRepos:
    - 'https://github.com/AlcarisMinecraftServer/alcaris_infra'
  destinations:
    - namespace: cloudflared-tunnel
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: alcaris-develop-gateway
  namespace: argocd
spec:
  description: The project of gateway system for the alcaris network (develop)
  sourceRepos:
    - 'https://github.com/AlcarisMinecraftServer/alcaris_infra'
  destinations:
    - namespace: alcaris-develop-gateway
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: alcaris-develop-minecraft
  namespace: argocd
spec:
  description: The project of minecraft server system for the alcaris network (develop)
  sourceRepos:
    - 'https://github.com/AlcarisMinecraftServer/alcaris_infra'
  destinations:
    - namespace: alcaris-develop-minecraft
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: alcaris-production-gateway
  namespace: argocd
spec:
  description: The project of gateway system for the alcaris network (production)
  sourceRepos:
    - 'https://github.com/AlcarisMinecraftServer/alcaris_infra'
  destinations:
    - namespace: alcaris-production-gateway
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: alcaris-production-minecraft
  namespace: argocd
spec:
  description: The project of minecraft server system for the alcaris network (production)
  sourceRepos:
    - 'https://github.com/AlcarisMinecraftServer/alcaris_infra'
  destinations:
    - namespace: alcaris-production-minecraft
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: alcaris-service
  namespace: argocd
spec:
  description: The project of service system for the alcaris network (prod)
  sourceRepos:
    - 'https://github.com/AlcarisMinecraftServer/alcaris_infra'
  destinations:
    - namespace: alcaris-service
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
