apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alcaris-production-minecraft

resources:
  - service.yaml
  - stateful-set.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: minecraft-production-s3-config-player
    files:
      - configs/plugins/AlcarisPlayer/config.yml


  - name: minecraft-production-s3-config-mythicmobs
    files:
      - configs/plugins/MythicMobs/mobs/ExampleMobs.yml
      - configs/plugins/MythicMobs/mobs/ForestCreatures.yml
      - configs/plugins/MythicMobs/mobs/SavannaCreatures.yml
      - configs/plugins/MythicMobs/mobs/StoneMountainCreatures.yml

      - configs/plugins/MythicMobs/skills/ExampleSkills.yml
      - configs/plugins/MythicMobs/skills/ForestGuardianSkills.yml
      - configs/plugins/MythicMobs/skills/SavannaSkills.yml
      - configs/plugins/MythicMobs/skills/StoneMountainSkills.yml