apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alcaris-production-gateway

resources:
  - service.yaml
  - stateful-set.yaml
  - configs/plugins-config.yaml
  - configs/velocity-config.yaml
