apiVersion: v1
kind: Service
metadata:
  name: gateway-production-velocity
spec:
  type: LoadBalancer
  ports:
    - name: gateway-production-velocity
      port: 25565
      protocol: TCP
      targetPort: gateway-production-velocity
  selector:
    app: gateway-production-velocity
  loadBalancerIP: 192.168.0.220