apiVersion: v1
kind: Service
metadata:
  name: velocity-production
spec:
  type: LoadBalancer
  ports:
    - name: velocity
      port: 25565
      protocol: TCP
      targetPort: velocity
  selector:
    app: velocity-production
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.0.220
