apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: velocity-production
  labels:
    app: velocity-production
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: velocity-production
  template:
    metadata:
      labels:
        app: velocity-production
    spec:
      containers:
        - name: velocity
          image: itzg/mc-proxy:java21
          resources:
            requests:
              memory: 512Mi
          env:
            - name: MEMORY
              value: 512m
            - name: TYPE
              value: VELOCITY
            - name: PLUGINS
              value: >-
                https://github.com/WiIIiam278/Velocitab/releases/download/1.7.4/Velocitab-1.7.4.jar,
                https://github.com/Lorenzo0111/RocketJoin/releases/download/2.4.2/RocketJoin-velocity-2.4.2.jar,
                https://github.com/kennytv/Maintenance/releases/download/4.3.0/Maintenance-Velocity-4.3.0.jar,
                https://github.com/4drian3d/SignedVelocity/releases/download/1.3.0/SignedVelocity-Proxy-1.3.0.jar,
                https://github.com/WiIIiam278/PAPIProxyBridge/releases/download/1.8/PAPIProxyBridge-Velocity-1.8.jar,
                https://github.com/AlcarisMinecraftServer/AlcarisChat/releases/download/v1.2.1/AlcarisChat-1.2.1.jar

          ports:
            - name: velocity
              containerPort: 25577
          startupProbe:
            tcpSocket:
              port: 25577
            failureThreshold: 6
            periodSeconds: 20
          volumeMounts:
            - name: velocity-production-config-velocity
              mountPath: /config/velocity.toml
              subPath: velocity.toml
            - name: velocity-production-config-velocity
              mountPath: /config/forwarding.secret
              subPath: forwarding.secret
            - name: velocity-production-config-plugins
              mountPath: /plugins/velocitab/config.yml
              subPath: velocitab-config.yml
            - name: velocity-production-config-plugins
              mountPath: /plugins/velocitab/tab_groups.yml
              subPath: velocitab-tab_groups.yml
            - name: velocity-production-config-plugins
              mountPath: /plugins/rocketjoin/config.yml
              subPath: rocketjoin-config.yml
      volumes:
        - name: velocity-production-config-velocity
          configMap:
            name: velocity-production-config-velocity
        - name: velocity-production-config-plugins
          configMap:
            name: velocity-production-config-plugins
