apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: cluster-wide-apps
  source:
    chart: mariadb-operator-crds
    repoURL: https://mariadb-operator.github.io/mariadb-operator
    targetRevision: 0.38.1
    helm:
      releaseName: mariadb-operator-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: mariadb-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
