apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database
resources:
  - stateful-set.yaml
  - service.yaml

# ファイル管理していい値だけ
secretGenerator:
  - name: postgres-secret
    type: Opaque
    literals:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=natsume
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
generatorOptions:
  disableNameSuffixHash: true
