apiVersion: v1
kind: ConfigMap
metadata:
  name: velocity-production-config-velocity
data:
  velocity.toml: |
    # Config version. Do not change this
    config-version = "2.7"

    # What port should the proxy be bound to? By default, we'll bind to all addresses on port 25577.
    bind = "0.0.0.0:25577"

    # What should be the MOTD? This gets displayed when the player adds your server to
    # their server list. Only MiniMessage format is accepted.
    motd = "             <gradient:#2d87e6:#2d87e6bb>Alcaris Server - A New Life</gradient><br>  <red>現在開発中です、詳細はDiscordサーバーを確認してください。</red>"

    # What should we display for the maximum number of players? (Velocity does not support a cap on the number of players online.)
    show-max-players = 100

    # Should we authenticate players with Mojang? By default, this is on.
    online-mode = true

    # Should the proxy enforce the new public key security standard? By default, this is on.
    force-key-authentication = true

    # If client's ISP/AS sent from this proxy is different from the one from Mojang's
    # authentication server, the player is kicked. This disallows some VPN and proxy
    # connections but is a weak form of protection.
    prevent-client-proxy-connections = false

    # Should we forward IP addresses and other data to backend servers?
    player-info-forwarding-mode = "MODERN"

    # If you are using modern or BungeeGuard IP forwarding, configure a file that contains a unique secret here.
    forwarding-secret-file = "forwarding.secret"

    # Announce whether or not your server supports Forge. If you run a modded server, we suggest turning this on.
    announce-forge = false

    # If enabled (default is false) and the proxy is in online mode, Velocity will kick
    # any existing player who is online if a duplicate connection attempt is made.
    kick-existing-players = false

    # Should Velocity pass server list ping requests to a backend server?
    ping-passthrough = "DISABLED"

    # If not enabled (default is true) player IP addresses will be replaced by <ip address withheld> in logs
    enable-player-address-logging = true

    [servers]
    s1 = "minecraft-production-s1.alcaris-production-minecraft.svc.cluster.local:25565"
    s2 = "minecraft-production-s2.alcaris-production-minecraft.svc.cluster.local:25565"
    s3 = "minecraft-production-s3.alcaris-production-minecraft.svc.cluster.local:25565"
    s4 = "minecraft-production-s4.alcaris-production-minecraft.svc.cluster.local:25565"

    # In what order we should try servers when a player logs in or is kicked from a server.
    try = ["s1"]

    [forced-hosts]
    # Configure your forced hosts here.
    "play.alcaris.net" = ["s1"]
    "play.s1.alcaris.net" = ["s1"]
    "play.s2.alcaris.net" = ["s2"]
    "play.s3.alcaris.net" = ["s3"]
    "play.s4.alcaris.net" = ["s4"]

    [advanced]
    # How large a Minecraft packet has to be before we compress it. Setting this to zero will
    # compress all packets, and setting it to -1 will disable compression entirely.
    compression-threshold = -1

    # How much compression should be done (from 0-9). The default is -1, which uses the
    # default level of 6.
    compression-level = -1

    # How fast (in milliseconds) are clients allowed to connect after the last connection? By
    # default, this is three seconds. Disable this by setting this to 0.
    login-ratelimit = 0

    # Specify a custom timeout for connection timeouts here. The default is five seconds.
    connection-timeout = 5000

    # Specify a read timeout for connections here. The default is 30 seconds.
    read-timeout = 30000

    # Enables compatibility with HAProxy's PROXY protocol. If you don't know what this is for, then
    # don't enable it.
    haproxy-protocol = true

    # Enables TCP fast open support on the proxy. Requires the proxy to run on Linux.
    tcp-fast-open = false

    # Enables BungeeCord plugin messaging channel support on Velocity.
    bungee-plugin-message-channel = true

    # Shows ping requests to the proxy from clients.
    show-ping-requests = false

    # By default, Velocity will attempt to gracefully handle situations where the user unexpectedly
    # loses connection to the server without an explicit disconnect message by attempting to fall the
    # user back, except in the case of read timeouts. BungeeCord will disconnect the user instead. You
    # can disable this setting to use the BungeeCord behavior.
    failover-on-unexpected-server-disconnect = true

    # Declares the proxy commands to 1.13+ clients.
    announce-proxy-commands = true

    # Enables the logging of commands
    log-command-executions = false

    # Enables logging of player connections when connecting to the proxy, switching servers
    # and disconnecting from the proxy.
    log-player-connections = true

    # Allows players transferred from other hosts via the
    # Transfer packet (Minecraft 1.20.5) to be received.
    accepts-transfers = false

    [query]
    # Whether to enable responding to GameSpy 4 query responses or not.
    enabled = false

    # If query is enabled, on what port should the query protocol listen on?
    port = 25577

    # This is the map name that is reported to the query services.
    map = "Velocity"

    # Whether plugins should be shown in query response by default or not
    show-plugins = false
  forwarding.secret: |
    ebz6gk84C1pn4H8b49ijLJG64HoHohFJ