apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database
resources:
  - stateful-set.yaml
  - service.yaml

secretGenerator:
  - name: mysql-secret
    type: Opaque
    literals:
      - TZ=Asia/Tokyo
      - MYSQL_USER=alcaris
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=alcaris
generatorOptions:
  disableNameSuffixHash: true
