apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-initdb
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS AlcarisInventory;
    CREATE DATABASE IF NOT EXISTS AlcarisDelivery;
    CREATE DATABASE IF NOT EXISTS AlcarisPlayer;

