apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database
resources:
  - stateful-set.yaml
  - service.yaml

secretGenerator:
  - name: mariadb-secret
    type: Opaque
    literals:
      - TZ=Asia/Tokyo
      - MARIADB_USER=alcaris
      - MARIADB_ROOT_PASSWORD=mariadb
      - MARIADB_DATABASE=alcaris
generatorOptions:
  disableNameSuffixHash: true
