apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

resources:
  - stateful-set.yaml
  - service.yaml
  - initdb-configmap.yaml

secretGenerator:
  - name: mariadb-secret
    type: Opaque
    literals:
      - root-password=zaq12wsx
      - user-password=zaq12wsx

generatorOptions:
  disableNameSuffixHash: true
