apiVersion: v1
kind: Service
metadata:
  name: admin-panel
  namespace: admin-panel
  labels:
    app: admin-panel
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
  selector:
    app: admin-panel
  loadBalancerIP: 192.168.0.240
