apiVersion: v1
kind: Service
metadata:
  name: admin-panel
  namespace: admin-panel
  labels:
    app: admin-panel
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: admin-panel
  selector:
    app: admin-panel
  loadBalancerIP: 192.168.0.240
