apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-panel
  namespace: admin-panel
  labels:
    app: admin-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-panel
  template:
    metadata:
      labels:
        app: admin-panel
    spec:
      containers:
        - name: admin-panel
          image: ghcr.io/alcarisminecraftserver/admin-panel:latest
          envFrom:
            - secretRef:
                name: admin-panel-secrets
      imagePullSecrets:
        - name: ghcr-secret
