apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-server-config
data:
  server.properties: |
    accepts-transfers=false
    allow-flight=false
    allow-nether=true
    broadcast-console-to-ops=true
    broadcast-rcon-to-ops=true
    bug-report-link=
    debug=false
    difficulty=hard
    enable-command-block=true
    enable-jmx-monitoring=false
    enable-query=false
    enable-rcon=false
    enable-status=true
    enforce-secure-profile=true
    enforce-whitelist=false
    entity-broadcast-range-percentage=100
    force-gamemode=false
    function-permission-level=2
    gamemode=survival
    generate-structures=true
    generator-settings={}
    hardcore=false
    hide-online-players=false
    initial-disabled-packs=
    initial-enabled-packs=vanilla
    level-name=world
    level-seed=
    level-type=minecraft\:flat
    log-ips=true
    max-chained-neighbor-updates=1000000
    max-players=100
    max-tick-time=60000
    max-world-size=29999984
    motd=A Minecraft Server
    network-compression-threshold=-1
    online-mode=false
    op-permission-level=4
    player-idle-timeout=0
    prevent-proxy-connections=false
    pvp=true
    query.port=25565
    rate-limit=0
    rcon.password=
    rcon.port=25575
    region-file-compression=deflate
    require-resource-pack=false
    resource-pack=
    resource-pack-id=
    resource-pack-prompt=
    resource-pack-sha1=
    server-ip=
    server-port=25565
    simulation-distance=12
    spawn-animals=true
    spawn-monsters=true
    spawn-npcs=true
    spawn-protection=16
    sync-chunk-writes=true
    text-filtering-config=
    use-native-transport=true
    view-distance=12
    white-list=false
  bukkit.yml: |
    settings:
      allow-end: true
      warn-on-overload: true
      permissions-file: permissions.yml
      update-folder: update
      plugin-profiling: false
      connection-throttle: 4000
      query-plugins: true
      deprecated-verbose: default
      shutdown-message: Server closed
      minimum-api: none
      use-map-color-cache: true
    spawn-limits:
      monsters: 70
      animals: 10
      water-animals: 5
      water-ambient: 20
      water-underground-creature: 5
      axolotls: 5
      ambient: 15
    chunk-gc:
      period-in-ticks: 600
    ticks-per:
      animal-spawns: 400
      monster-spawns: 1
      water-spawns: 1
      water-ambient-spawns: 1
      water-underground-creature-spawns: 1
      axolotl-spawns: 1
      ambient-spawns: 1
      autosave: 6000
    aliases: now-in-commands.yml
  spigot.yml: |
    messages:
      whitelist: You are not whitelisted on this server!
      unknown-command: Unknown command. Type "/help" for help.
      server-full: The server is full!
      outdated-client: Outdated client! Please use {0}
      outdated-server: Outdated server! I'm still on {0}
      restart: Server is restarting
    settings:
      debug: false
      save-user-cache-on-stop-only: false
      sample-count: 12
      log-villager-deaths: true
      log-named-deaths: true
      timeout-time: 60
      restart-on-crash: true
      restart-script: ./start.sh
      netty-threads: 4
      user-cache-size: 1000
      player-shuffle: 0
      attribute:
        maxAbsorption:
          max: 2048.0
        maxHealth:
          max: 2048.0
        movementSpeed:
          max: 2048.0
        attackDamage:
          max: 2048.0
      bungeecord: false
      moved-too-quickly-multiplier: 10.0
      moved-wrongly-threshold: 0.0625
    world-settings:
      default:
        below-zero-generation-in-existing-chunks: true
        unload-frozen-chunks: false
        entity-activation-range:
          animals: 32
          monsters: 32
          raiders: 64
          misc: 16
          water: 16
          villagers: 32
          flying-monsters: 32
          wake-up-inactive:
            animals-max-per-tick: 4
            animals-every: 1200
            animals-for: 100
            monsters-max-per-tick: 8
            monsters-every: 400
            monsters-for: 100
            villagers-max-per-tick: 4
            villagers-every: 600
            villagers-for: 100
            flying-monsters-max-per-tick: 8
            flying-monsters-every: 200
            flying-monsters-for: 100
          villagers-work-immunity-after: 100
          villagers-work-immunity-for: 20
          villagers-active-for-panic: true
          tick-inactive-villagers: true
          ignore-spectators: false
        arrow-despawn-rate: 1200
        trident-despawn-rate: 1200
        growth:
          cactus-modifier: 100
          cane-modifier: 100
          melon-modifier: 100
          mushroom-modifier: 100
          pumpkin-modifier: 100
          sapling-modifier: 100
          beetroot-modifier: 100
          carrot-modifier: 100
          potato-modifier: 100
          torchflower-modifier: 100
          wheat-modifier: 100
          netherwart-modifier: 100
          vine-modifier: 100
          cocoa-modifier: 100
          bamboo-modifier: 100
          sweetberry-modifier: 100
          kelp-modifier: 100
          twistingvines-modifier: 100
          weepingvines-modifier: 100
          cavevines-modifier: 100
          glowberry-modifier: 100
          pitcherplant-modifier: 100
        mob-spawn-range: 8
        item-despawn-rate: 6000
        nerf-spawner-mobs: false
        thunder-chance: 100000
        seed-village: 10387312
        seed-desert: 14357617
        seed-igloo: 14357618
        seed-jungle: 14357619
        seed-swamp: 14357620
        seed-monument: 10387313
        seed-shipwreck: 165745295
        seed-ocean: 14357621
        seed-outpost: 165745296
        seed-endcity: 10387313
        seed-slime: 987234911
        seed-nether: 30084232
        seed-mansion: 10387319
        seed-fossil: 14357921
        seed-portal: 34222645
        seed-ancientcity: 20083232
        seed-trailruins: 83469867
        seed-trialchambers: 94251327
        seed-buriedtreasure: 10387320
        seed-mineshaft: default
        seed-stronghold: default
        max-tick-time:
          tile: 50
          entity: 50
        max-tnt-per-tick: 100
        entity-tracking-range:
          players: 128
          animals: 96
          monsters: 96
          misc: 96
          display: 128
          other: 64
        enable-zombie-pigmen-portal-spawns: true
        zombie-aggressive-towards-villager: true
        wither-spawn-sound-radius: 0
        end-portal-sound-radius: 0
        hanging-tick-frequency: 100
        dragon-death-sound-radius: 0
        ticks-per:
          hopper-transfer: 8
          hopper-check: 1
        hopper-amount: 1
        hopper-can-load-chunks: false
        hunger:
          jump-walk-exhaustion: 0.05
          jump-sprint-exhaustion: 0.2
          combat-exhaustion: 0.1
          regen-exhaustion: 6.0
          swim-multiplier: 0.01
          sprint-multiplier: 0.1
          other-multiplier: 0.0
        merge-radius:
          item: 0.5
          exp: -1.0
        simulation-distance: default
        view-distance: default
        verbose: false
    commands:
      spam-exclusions: []
      log: true
      replace-commands: []
      tab-complete: 0
      send-namespaced: true
      silent-commandblock-console: false
    advancements:
      disable-saving: false
      disabled: []
    players:
      disable-saving: false
    config-version: 12
    stats:
      disable-saving: false
      forced-stats: {}
  paper-global.yml: |
    _version: 29
    block-updates:
      disable-chorus-plant-updates: false
      disable-mushroom-block-updates: false
      disable-noteblock-updates: false
      disable-tripwire-updates: false
    chunk-loading-advanced:
      auto-config-send-distance: true
      player-max-concurrent-chunk-generates: 0
      player-max-concurrent-chunk-loads: 0
    chunk-loading-basic:
      player-max-chunk-generate-rate: -1.0
      player-max-chunk-load-rate: 100.0
      player-max-chunk-send-rate: 75.0
    chunk-system:
      gen-parallelism: default
      io-threads: -1
      worker-threads: -1
    collisions:
      enable-player-collisions: true
      send-full-pos-for-hard-colliding-entities: true
    commands:
      fix-target-selector-tag-completion: true
      suggest-player-names-when-null-tab-completions: true
      time-command-affects-all-worlds: false
    console:
      enable-brigadier-completions: true
      enable-brigadier-highlighting: true
      has-all-permissions: false
    item-validation:
      book:
        author: 8192
        page: 16384
        title: 8192
      book-size:
        page-max: 2560
        total-multiplier: 0.98
      display-name: 8192
      lore-line: 8192
      resolve-selectors-in-books: false
    logging:
      deobfuscate-stacktraces: true
    messages:
      kick:
        authentication-servers-down: <lang:multiplayer.disconnect.authservers_down>
        connection-throttle: Connection throttled! Please wait before reconnecting.
        flying-player: <lang:multiplayer.disconnect.flying>
        flying-vehicle: <lang:multiplayer.disconnect.flying>
      no-permission: <red>I'm sorry, but you do not have permission to perform this command.
        Please contact the server administrators if you believe that this is in error.
      use-display-name-in-quit-message: false
    misc:
      chat-threads:
        chat-executor-core-size: -1
        chat-executor-max-size: -1
      client-interaction-leniency-distance: default
      compression-level: default
      fix-entity-position-desync: true
      load-permissions-yml-before-plugins: true
      max-joins-per-tick: 5
      region-file-cache-size: 256
      strict-advancement-dimension-check: false
      use-alternative-luck-formula: false
      use-dimension-type-for-custom-spawners: false
    packet-limiter:
      all-packets:
        action: KICK
        interval: 7.0
        max-packet-rate: 500.0
      kick-message: <red><lang:disconnect.exceeded_packet_rate>
      overrides:
        ServerboundPlaceRecipePacket:
          action: DROP
          interval: 4.0
          max-packet-rate: 5.0
    player-auto-save:
      max-per-tick: -1
      rate: -1
    proxies:
      bungee-cord:
        online-mode: true
      proxy-protocol: false
      velocity:
        enabled: true
        online-mode: true
        secret: 'ebz6gk84C1pn4H8b49ijLJG64HoHohFJ'
    scoreboards:
      save-empty-scoreboard-teams: true
      track-plugin-scoreboards: false
    spam-limiter:
      incoming-packet-threshold: 300
      recipe-spam-increment: 1
      recipe-spam-limit: 20
      tab-spam-increment: 1
      tab-spam-limit: 500
    spark:
      enable-immediately: false
      enabled: true
    timings:
      enabled: false
      hidden-config-entries:
      - database
      - proxies.velocity.secret
      history-interval: 300
      history-length: 3600
      server-name: Unknown Server
      server-name-privacy: false
      url: https://timings.aikar.co/
      verbose: true
    unsupported-settings:
      allow-headless-pistons: false
      allow-permanent-block-break-exploits: false
      allow-piston-duplication: false
      allow-tripwire-disarming-exploits: false
      allow-unsafe-end-portal-teleportation: false
      compression-format: ZLIB
      perform-username-validation: true
      skip-vanilla-damage-tick-when-shield-blocked: false
    watchdog:
      early-warning-delay: 10000
      early-warning-every: 5000
