apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: discord-bot
  labels:
    app: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
        - name: discord-bot
          image: ghcr.io/alcarisminecraftserver/discord-bot:latest
          env:
            - name: PROD_GUILD
              value: "1097098741049200680"
            - name: TEST_GUILD
              value: "989864826950008882"
          envFrom:
            - secretRef:
                name: discord-bot-secrets
      imagePullSecrets:
        - name: ghcr-secret