apiVersion: v1
kind: Service
metadata:
  name: minecraft-develop-s4
  labels:
    app: minecraft-server
    mcserver: develop-s4
spec:
  type: ClusterIP
  ports:
    - name: minecraft
      port: 25565
      protocol: TCP
      targetPort: minecraft
  selector:
    mcserver: develop-s4
  loadBalancerIP: 192.168.0.234
