apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alcaris-production-minecraft

resources:
  - service.yaml
  - stateful-set.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: minecraft-production-s2-config-player
    files:
      - configs/plugins/AlcarisPlayer/config.yml

  - name: minecraft-production-s2-config-alcarisresource
    files:
      - configs/plugins/AlcarisResource/npc_config.yml
      - configs/plugins/AlcarisResource/mobs/mobs-resource-lvl1.yml
      - configs/plugins/AlcarisResource/blocks/blocks-resource-lvl1.yml

  - name: minecraft-production-s2-config-alcarisitems
    files:
      - configs/plugins/AlcarisItems/config.yml