apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alcaris-production-minecraft

resources:
  - service.yaml
  - stateful-set.yaml

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
  - name: minecraft-production-server2-config-alcarisinventoryshare
    files:
      - configs/plugins/AlcarisInventoryShare/config.yml