server:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 90
    targetMemoryUtilizationPercentage: 175
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 192Mi
  pdb:
    enabled: true
    minAvailable: 1
    maxUnavailable: 1

configs:
  cm:
    create: true
    application.instanceLabelKey: argocd.argoproj.io/instance
    kustomize.buildOptions: --load-restrictor LoadRestrictionsNone
    url: https://argocd.onp-k8s.admin.alcaris.net
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: Ov23liZzAQdgJHeFA1Mb
            clientSecret: $argocd-github-oauth-app-secret:ARGOCD_GITHUB_OAUTH_APP_SECRET
            orgs:
              - name: AlcarisMinecraftServer
                teams:
                  - onp-admin-argocd
  rbac:
    policy.csv: |
      g, AlcarisMinecraftServer:onp-admin-argocd, role:admin
    policy.default: role:readonly
