apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  namespace: alcaris-production-minecraft
  name: inventory-db-credentials
spec:
  forceRegenerate: false
  fields:
    - fieldName: "password"
      encoding: "hex"
      length: "32"

---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  namespace: alcaris-production-minecraft
  name: inventory
spec:
  mariaDbRef:
    name: mariadb
    waitForIt: true
  passwordSecretKeyRef:
    name: inventory-db-credentials
    key: password

---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  namespace: alcaris-production-minecraft
  name: inventory
spec:
  mariaDbRef:
    name: mariadb
    waitForIt: true
  characterSet: utf8mb4
  collate: utf8mb4_general_ci
  name: inventory

---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  namespace: alcaris-production-minecraft
  name: inventory
spec:
  mariaDbRef:
    name: mariadb
    waitForIt: true
  privileges:
    - "ALL"
  database: "inventory"
  table: "*"
  username: "inventory"
  grantOption: false
