apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-common-config-ops
data:
  ops.json: |
    [
      {
        "uuid": "1e34df52-e86b-4ef5-b93c-41c3743ffd6f",
        "name": "namakemono_san",
        "level": 4,
        "bypassesPlayerLimit": false
      },
      {
        "uuid": "683d5c82-a124-47dc-9b95-f859d3b310d2",
        "name": "somen1000",
        "level": 4,
        "bypassesPlayerLimit": false
      },
      {
        "uuid": "8584fd8e-22e4-476c-acf9-bcff714efa21",
        "name": "gamutyan",
        "level": 4,
        "bypassesPlayerLimit": false
      }
    ]