apiVersion: v1
kind: Service
metadata:
  name: natsume-backend
  namespace: natsume-backend
  labels:
    app: natsume-backend
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: natsume-backend
  loadBalancerIP: 192.168.0.242
