apiVersion: v1
kind: Service
metadata:
  name: minecraft-develop-s3
  labels:
    app: minecraft-server
    mcserver: develop-s3
spec:
  type: ClusterIP
  ports:
    - name: minecraft
      port: 25565
      protocol: TCP
      targetPort: minecraft
  selector:
    mcserver: develop-s3
