apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-tunnel-config
  namespace: cloudflared-tunnel
data:
  config.yaml: |
    tunnel: onp-k8s--http--argocd
    ingress:
      - hostname: argocd.onp-k8s.admin.alcaris.net
        service: https://argocd-server.argocd:443
      - service: http_status:404
