apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-argocd
  namespace: cloudflared-tunnel
  labels:
    app: cloudflared-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-argocd
  template:
    metadata:
      labels:
        app: cloudflared-argocd
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2024.3.1
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token
            - $(TUNNEL_TOKEN)
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-tunnel-token
                  key: token
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared
      volumes:
        - name: config
          configMap:
            name: cloudflared-tunnel-config
