apiVersion: v1
kind: Service
metadata:
  name: test-server-lb
  namespace: minecraft
spec:
  type: LoadBalancer
  selector:
    app: minecraft-server
  ports:
  - name: minecraft
    protocol: TCP
    port: 25565
    targetPort: 25565