apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-lb
spec:
  selector:
    app: minecraft-server
  ports:
  - name: minecraft
    protocol: TCP
    port: 25565
    targetPort: 25565
  type: LoadBalancer
  loadBalancerIP: 192.168.0.240