apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alcaris-production-minecraft

resources:
  - service.yaml
  - stateful-set.yaml

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
  - name: minecraft-production-server1-config-multiverse-core
    files:
      - configs/plugins/Multiverse-Core/worlds.yml

  - name: minecraft-production-server1-config-whitelist-message
    files:
      - configs/plugins/Whitelist-Message/config.yml

  - name: minecraft-production-server1-config-alcarisinventoryshare
    files:
      - configs/plugins/AlcarisInventoryShare/config.yml

  - name: minecraft-production-server1-config-autoopgive
    files:
      - configs/plugins/AutoOPGive/config.yml