apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alcaris-production-minecraft

resources:
  - service.yaml
  - stateful-set.yaml
  - configs/plugins/Multiverse-Core/worlds.yml