apiVersion: v1
kind: Service
metadata:
  name: minecraft-production-s1
  labels:
    app: minecraft-server
    mcserver: production-s1
spec:
  type: ClusterIP
  ports:
    - name: minecraft
      port: 25565
      protocol: TCP
      targetPort: minecraft
  selector:
    mcserver: production-s1
  loadBalancerIP: 192.168.0.221
