apiVersion: apps/v1
kind: Deployment
metadata:
  name: natsume-frontend
  namespace: natsume-frontend
  labels:
    app: natsume-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: natsume-frontend
  template:
    metadata:
      labels:
        app: natsume-frontend
    spec:
      containers:
        - name: natsume-frontend
          image: ghcr.io/alcarisminecraftserver/natsume-frontend:latest
          envFrom:
            - secretRef:
                name: natsume-frontend-secrets
      imagePullSecrets:
        - name: ghcr-secret
