apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-tunnel-config
  namespace: cloudflared-tunnel
data:
  config.yaml: |
    tunnel: onp-k8s--http--cloudflared-tunnel
    credentials-file: /etc/cloudflared/cloudflared-tunnel.json
    ingress:
      - hostname: portal.onp-k8s.admin.alcaris.net
        service: http://admin-panel.alcaris-service.svc.cluster.local:3000

      - hostname: argocd.onp-k8s.admin.alcaris.net
        service: http://argocd-server.argocd.svc.cluster.local:80

      - hostname: proxmox.onp.admin.alcaris.net
        service: https://192.168.0.110:8006
      
      - service: http_status:404
