apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-tunnel-config
  namespace: cloudflared-tunnel
data:
  config.yaml: |
    tunnel: onp-k8s-cloudflared-tunnel
    credentials-file: /etc/cloudflared/cloudflared-tunnel.json
    ingress:
      - hostname: portal.onp-k8s.admin.alcaris.net
        service: http://admin-panel.alcaris-service.svc.cluster.local:3000

      - hostname: argocd.onp-k8s.admin.alcaris.net
        service: https://argocd-server.argocd.svc.cluster.local:80
        originRequest:
          noTLSVerify: true

      - hostname: grafana.onp.admin.alcaris.net
        service: http://192.168.0.182:3000

      - hostname: zabbix.onp.admin.alcaris.net
        service: http://192.168.0.181:8080

      - hostname: proxmox.onp.admin.alcaris.net
        service: https://192.168.0.110:8006
        originRequest:
          noTLSVerify: true

      - hostname: natsume.onp-k8s.admin.alcaris.net
        service: http://natsume-frontend.alcaris-service.svc.cluster.local:80

      - hostname: api-natsume.onp-k8s.admin.alcaris.net
        service: http://natsume-backend.alcaris-service.svc.cluster.local:9000

      - service: http_status:404
