apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-tunnel
  namespace: cloudflared-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-tunnel
  template:
    metadata:
      labels:
        app: cloudflared-tunnel
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2024.4.0
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config.yaml
            - run
          volumeMounts:
            - name: cloudflared-config
              mountPath: /etc/cloudflared
              readOnly: true
      volumes:
        - name: cloudflared-config
          projected:
            sources:
              - configMap:
                  name: cloudflared-tunnel-config
              - secret:
                  name: cloudflared-credentials
