apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alcaris-production-minecraft

resources:
  - service.yaml
  - stateful-set.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: minecraft-production-s4-config-player
    files:
      - configs/plugins/AlcarisPlayer/config.yml

  - name: minecraft-production-s4-config-miningminigamev2
    files:
      - configs/plugins/MiningMinigameV2/config.yml

  - name: minecraft-production-s4-config-fastasyncworldedit
    files:
      - configs/plugins/FastAsyncWorldEdit/config.yml