apiVersion: v1
kind: Service
metadata:
  name: velocity
spec:
  type: LoadBalancer
<<<<<<< HEAD
  loadBalancerClass: io.cilium/bgp-control-plane
  externalTrafficPolicy: Local
=======
>>>>>>> parent of cdf09f0 (feat: 検証)
  ports:
    - name: velocity
      port: 25565
      protocol: TCP
      targetPort: velocity
  selector:
    app: velocity
  loadBalancerIP: 192.168.0.230