apiVersion: v1
kind: Service
metadata:
  name: velocity
  annotations:
    "io.cilium/lb-ipam-ips": "192.168.0.230"
spec:
  type: LoadBalancer
  loadBalancerClass: io.cilium/bgp-control-plane
  externalTrafficPolicy: Local
  ports:
    - name: velocity
      port: 25565
      protocol: TCP
      targetPort: velocity
  selector:
    app: velocity
