apiVersion: v1
kind: Service
metadata:
  name: velocity-develop
spec:
  type: LoadBalancer
  ports:
    - name: velocity
      port: 25566
      protocol: TCP
      targetPort: velocity
  selector:
    app: velocity-develop
  loadBalancerIP: 192.168.0.230
