apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: velocity
  labels:
    app: velocity
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      containers:
        - name: velocity
          image: itzg/mc-proxy:java21
          resources:
            requests:
              memory: 512Mi
          env:
            - name: MEMORY
              value: 512m
            - name: TYPE
              value: VELOCITY
              
            - name: PLUGINS
              value: >-
                https://github.com/WiIIiam278/Velocitab/releases/download/1.7.4/Velocitab-1.7.4.jar,
                https://github.com/Lorenzo0111/RocketJoin/releases/download/2.4.2/RocketJoin-velocity-2.4.2.jar,
                https://github.com/WiIIiam278/PAPIProxyBridge/releases/download/1.7.2/PAPIProxyBridge-Velocity-1.7.2.jar,
                https://github.com/jpenilla/MiniMOTD/releases/download/v2.1.5/minimotd-velocity-2.1.5.jar,
                https://github.com/kennytv/Maintenance/releases/download/4.3.0/Maintenance-Velocity-4.3.0.jar,
                https://github.com/4drian3d/SignedVelocity/releases/download/1.3.0/SignedVelocity-Proxy-1.3.0.jar,
                https://github.com/4drian3d/VPacketEvents/releases/download/1.1.0/VPacketEvents-1.1.0.jar
          ports:
            - name: velocity
              containerPort: 25577
          startupProbe:
            tcpSocket:
              port: 25577
            failureThreshold: 6
            periodSeconds: 20
          volumeMounts:
            - name: gateway-config-velocity
              mountPath: /config/velocity.toml
              subPath: velocity.toml
            - name: gateway-config-velocity
              mountPath: /config/forwarding.secret
              subPath: forwarding.secret
      volumes:
        - name: gateway-config-velocity
          configMap:
            name: gateway-config-velocity
