apiVersion: v1
kind: ConfigMap
metadata:
  name: velocity-config
data:
  velocity.toml: |
    config-version = "2.7"

    bind = "0.0.0.0:25577"
    motd = "<#09add3>A Velocity Server"
    show-max-players = 100
    online-mode = true
    force-key-authentication = true
    prevent-client-proxy-connections = false
    player-info-forwarding-mode = "modern"
    forwarding-secret-file = "forwarding.secret"
    announce-forge = false
    kick-existing-players = false
    ping-passthrough = "DISABLED"
    enable-player-address-logging = true

    [servers]
    s1 = "minecraft-develop-server-1.alcaris-develop-minecraft.svc.cluster.local:25565"

    try = ["s1"]

    [forced-hosts]

    [advanced]
    compression-threshold = 256
    compression-level = -1
    login-ratelimit = 3000
    connection-timeout = 5000
    read-timeout = 30000
    haproxy-protocol = false
    tcp-fast-open = false
    bungee-plugin-message-channel = true
    show-ping-requests = false
    failover-on-unexpected-server-disconnect = true
    announce-proxy-commands = true
    log-command-executions = false
    log-player-connections = true
    accepts-transfers = false
    enable-reuse-port = false

    [query]
    enabled = false
    port = 25565
    map = "Velocity"
    show-plugins = false
  forwarding.secret: |
    ebz6gk84C1pn4H8b49ijLJG64HoHohFJ