apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-develop-s1
  labels:
    app: minecraft-develop-s1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-develop-s1
  template:
    metadata:
      labels:
        app: minecraft-develop-s1
        mcserver: develop-s1
    spec:
      containers:
        - image: itzg/minecraft-server:latest
          name: minecraft-server
          env:
            - name: MEMORY
              value: 4G
            - name: TYPE
              value: PAPER
            - name: VERSION
              value: "1.21.1"
            - name: EULA
              value: "TRUE"
          ports:
            - name: minecraft
              containerPort: 25565
          volumeMounts:
            - name: minecraft-server-config
              mountPath: server.properties
              subPath: server.properties
            - name: minecraft-server-config
              mountPath: bukkit.yml
              subPath: bukkit.yml
            - name: minecraft-server-config
              mountPath: spigot.yml
              subPath: spigot.yml
            - name: minecraft-server-config
              mountPath: /config/paper-global.yml
              subPath: paper-global.yml

            - name: minecraft-ops-config
              mountPath: ops.json
              subPath: ops.json

            - name: minecraft-server-data
              mountPath: /data
      volumes:
        - name: minecraft-server-config
          configMap:
            name: minecraft-server-config
        - name: minecraft-ops-config
          configMap:
            name: minecraft-ops-config
  volumeClaimTemplates:
    - metadata:
        name: minecraft-server-data
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
